plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.2'
}

group = 'dev.xdpxi'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
    flatDir { dir "libs" }
}

dependencies {
    implementation 'net.minestom:minestom:2026.06.20-26.1.2'
    implementation 'org.apache.logging.log4j:log4j-core:2.26.0'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.26.0'
    implementation 'org.yaml:snakeyaml:2.6'
    implementation 'com.formdev:flatlaf:3.7.1'
    implementation 'io.github.togar2:MinestomPvP:2026.05.30-26.1.1'
    implementation 'dev.hollowcube:polar:1.16.0'
    implementation 'it.unimi.dsi:fastutil:8.5.18'
    implementation 'io.github.TogAr2:MinestomFluids'

    testImplementation platform('org.junit:junit-bom:6.1.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }

    withJavadocJar()
    withSourcesJar()
}

tasks {
    jar {
        manifest {
            attributes["Main-Class"] = "dev.xdpxi.swiftmc.Main"
        }
    }

    build {
        dependsOn(shadowJar)
    }

    shadowJar {
        mergeServiceFiles()
        archiveClassifier.set("")
    }

    test {
        useJUnitPlatform()
    }

    build {
        dependsOn(javadocJar, sourcesJar)
    }
}
